name: io_uring
description: Blazing fast async `dart:io` implementation based on `io_uring`

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  build: ^2.1.1
  build_runner: ^2.1.5
  extra_pedantic: ^1.5.0
  scratch_space: ^1.0.1
